/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bridge from "./Bridge";
export type { bridge };
import type * as distributorSol from "./Distributor.sol";
export type { distributorSol };
import type * as foeSol from "./FOE.sol";
export type { foeSol };
import type * as histopiaNftSol from "./HistopiaNFT.sol";
export type { histopiaNftSol };
import type * as nft from "./NFT";
export type { nft };
import type * as multicallSol from "./multicall.sol";
export type { multicallSol };
export type { Challenger } from "./Challenger";
export type { ERA } from "./ERA";
export type { Resources } from "./Resources";
