/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as distributorSol from "./Distributor.sol";
export type { distributorSol };
import type * as foeSol from "./FOE.sol";
export type { foeSol };
import type * as histopiaNftSol from "./HistopiaNFT.sol";
export type { histopiaNftSol };
export type { Challenger } from "./Challenger";
export type { ERA } from "./ERA";
export type { Resources } from "./Resources";
