/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as foeSol from "./FOE.sol";
export type { foeSol };
import type * as histopiaNftSol from "./HistopiaNFT.sol";
export type { histopiaNftSol };
export type { ERA } from "./ERA";
export type { Lock } from "./Lock";
