/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ResourcesInterface extends utils.Interface {
  functions: {
    "BOW()": FunctionFragment;
    "BREAD()": FunctionFragment;
    "CATTLE()": FunctionFragment;
    "DATE()": FunctionFragment;
    "EGG()": FunctionFragment;
    "FLOUR()": FunctionFragment;
    "GOLD()": FunctionFragment;
    "GRAPE()": FunctionFragment;
    "HEN()": FunctionFragment;
    "IRON()": FunctionFragment;
    "MEAT()": FunctionFragment;
    "MILK()": FunctionFragment;
    "PIG()": FunctionFragment;
    "RICE()": FunctionFragment;
    "SHEEP()": FunctionFragment;
    "SHIELD()": FunctionFragment;
    "SPEAR()": FunctionFragment;
    "STONE()": FunctionFragment;
    "SWORD()": FunctionFragment;
    "WHEAT()": FunctionFragment;
    "WOOD()": FunctionFragment;
    "WOOL()": FunctionFragment;
    "balanceOf(address,uint256)": FunctionFragment;
    "balanceOfBatch(address[],uint256[])": FunctionFragment;
    "isApprovedForAll(address,address)": FunctionFragment;
    "mint(address,uint256,uint256,bytes)": FunctionFragment;
    "mintBatch(address,uint256[],uint256[],bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "safeTransferFrom(address,address,uint256,uint256,bytes)": FunctionFragment;
    "setApprovalForAll(address,bool)": FunctionFragment;
    "setURI(string)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "uri(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BOW"
      | "BREAD"
      | "CATTLE"
      | "DATE"
      | "EGG"
      | "FLOUR"
      | "GOLD"
      | "GRAPE"
      | "HEN"
      | "IRON"
      | "MEAT"
      | "MILK"
      | "PIG"
      | "RICE"
      | "SHEEP"
      | "SHIELD"
      | "SPEAR"
      | "STONE"
      | "SWORD"
      | "WHEAT"
      | "WOOD"
      | "WOOL"
      | "balanceOf"
      | "balanceOfBatch"
      | "isApprovedForAll"
      | "mint"
      | "mintBatch"
      | "owner"
      | "renounceOwnership"
      | "safeBatchTransferFrom"
      | "safeTransferFrom"
      | "setApprovalForAll"
      | "setURI"
      | "supportsInterface"
      | "transferOwnership"
      | "uri"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "BOW", values?: undefined): string;
  encodeFunctionData(functionFragment: "BREAD", values?: undefined): string;
  encodeFunctionData(functionFragment: "CATTLE", values?: undefined): string;
  encodeFunctionData(functionFragment: "DATE", values?: undefined): string;
  encodeFunctionData(functionFragment: "EGG", values?: undefined): string;
  encodeFunctionData(functionFragment: "FLOUR", values?: undefined): string;
  encodeFunctionData(functionFragment: "GOLD", values?: undefined): string;
  encodeFunctionData(functionFragment: "GRAPE", values?: undefined): string;
  encodeFunctionData(functionFragment: "HEN", values?: undefined): string;
  encodeFunctionData(functionFragment: "IRON", values?: undefined): string;
  encodeFunctionData(functionFragment: "MEAT", values?: undefined): string;
  encodeFunctionData(functionFragment: "MILK", values?: undefined): string;
  encodeFunctionData(functionFragment: "PIG", values?: undefined): string;
  encodeFunctionData(functionFragment: "RICE", values?: undefined): string;
  encodeFunctionData(functionFragment: "SHEEP", values?: undefined): string;
  encodeFunctionData(functionFragment: "SHIELD", values?: undefined): string;
  encodeFunctionData(functionFragment: "SPEAR", values?: undefined): string;
  encodeFunctionData(functionFragment: "STONE", values?: undefined): string;
  encodeFunctionData(functionFragment: "SWORD", values?: undefined): string;
  encodeFunctionData(functionFragment: "WHEAT", values?: undefined): string;
  encodeFunctionData(functionFragment: "WOOD", values?: undefined): string;
  encodeFunctionData(functionFragment: "WOOL", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfBatch",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBatch",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeBatchTransferFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setURI",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "uri",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "BOW", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "BREAD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "CATTLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DATE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "EGG", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FLOUR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "GOLD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "GRAPE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "HEN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "IRON", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MEAT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MILK", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PIG", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RICE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SHEEP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SHIELD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SPEAR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "STONE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SWORD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WHEAT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WOOD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WOOL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintBatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeBatchTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uri", data: BytesLike): Result;

  events: {
    "ApprovalForAll(address,address,bool)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "TransferBatch(address,address,address,uint256[],uint256[])": EventFragment;
    "TransferSingle(address,address,address,uint256,uint256)": EventFragment;
    "URI(string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferBatch"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferSingle"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "URI"): EventFragment;
}

export interface ApprovalForAllEventObject {
  account: string;
  operator: string;
  approved: boolean;
}
export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean],
  ApprovalForAllEventObject
>;

export type ApprovalForAllEventFilter = TypedEventFilter<ApprovalForAllEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface TransferBatchEventObject {
  operator: string;
  from: string;
  to: string;
  ids: BigNumber[];
  values: BigNumber[];
}
export type TransferBatchEvent = TypedEvent<
  [string, string, string, BigNumber[], BigNumber[]],
  TransferBatchEventObject
>;

export type TransferBatchEventFilter = TypedEventFilter<TransferBatchEvent>;

export interface TransferSingleEventObject {
  operator: string;
  from: string;
  to: string;
  id: BigNumber;
  value: BigNumber;
}
export type TransferSingleEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  TransferSingleEventObject
>;

export type TransferSingleEventFilter = TypedEventFilter<TransferSingleEvent>;

export interface URIEventObject {
  value: string;
  id: BigNumber;
}
export type URIEvent = TypedEvent<[string, BigNumber], URIEventObject>;

export type URIEventFilter = TypedEventFilter<URIEvent>;

export interface Resources extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ResourcesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BOW(overrides?: CallOverrides): Promise<[BigNumber]>;

    BREAD(overrides?: CallOverrides): Promise<[BigNumber]>;

    CATTLE(overrides?: CallOverrides): Promise<[BigNumber]>;

    DATE(overrides?: CallOverrides): Promise<[BigNumber]>;

    EGG(overrides?: CallOverrides): Promise<[BigNumber]>;

    FLOUR(overrides?: CallOverrides): Promise<[BigNumber]>;

    GOLD(overrides?: CallOverrides): Promise<[BigNumber]>;

    GRAPE(overrides?: CallOverrides): Promise<[BigNumber]>;

    HEN(overrides?: CallOverrides): Promise<[BigNumber]>;

    IRON(overrides?: CallOverrides): Promise<[BigNumber]>;

    MEAT(overrides?: CallOverrides): Promise<[BigNumber]>;

    MILK(overrides?: CallOverrides): Promise<[BigNumber]>;

    PIG(overrides?: CallOverrides): Promise<[BigNumber]>;

    RICE(overrides?: CallOverrides): Promise<[BigNumber]>;

    SHEEP(overrides?: CallOverrides): Promise<[BigNumber]>;

    SHIELD(overrides?: CallOverrides): Promise<[BigNumber]>;

    SPEAR(overrides?: CallOverrides): Promise<[BigNumber]>;

    STONE(overrides?: CallOverrides): Promise<[BigNumber]>;

    SWORD(overrides?: CallOverrides): Promise<[BigNumber]>;

    WHEAT(overrides?: CallOverrides): Promise<[BigNumber]>;

    WOOD(overrides?: CallOverrides): Promise<[BigNumber]>;

    WOOL(overrides?: CallOverrides): Promise<[BigNumber]>;

    balanceOf(
      account: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    balanceOfBatch(
      accounts: PromiseOrValue<string>[],
      ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    isApprovedForAll(
      account: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    mint(
      account: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    mintBatch(
      to: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    safeBatchTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    safeTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setURI(
      uri_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    uri(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  BOW(overrides?: CallOverrides): Promise<BigNumber>;

  BREAD(overrides?: CallOverrides): Promise<BigNumber>;

  CATTLE(overrides?: CallOverrides): Promise<BigNumber>;

  DATE(overrides?: CallOverrides): Promise<BigNumber>;

  EGG(overrides?: CallOverrides): Promise<BigNumber>;

  FLOUR(overrides?: CallOverrides): Promise<BigNumber>;

  GOLD(overrides?: CallOverrides): Promise<BigNumber>;

  GRAPE(overrides?: CallOverrides): Promise<BigNumber>;

  HEN(overrides?: CallOverrides): Promise<BigNumber>;

  IRON(overrides?: CallOverrides): Promise<BigNumber>;

  MEAT(overrides?: CallOverrides): Promise<BigNumber>;

  MILK(overrides?: CallOverrides): Promise<BigNumber>;

  PIG(overrides?: CallOverrides): Promise<BigNumber>;

  RICE(overrides?: CallOverrides): Promise<BigNumber>;

  SHEEP(overrides?: CallOverrides): Promise<BigNumber>;

  SHIELD(overrides?: CallOverrides): Promise<BigNumber>;

  SPEAR(overrides?: CallOverrides): Promise<BigNumber>;

  STONE(overrides?: CallOverrides): Promise<BigNumber>;

  SWORD(overrides?: CallOverrides): Promise<BigNumber>;

  WHEAT(overrides?: CallOverrides): Promise<BigNumber>;

  WOOD(overrides?: CallOverrides): Promise<BigNumber>;

  WOOL(overrides?: CallOverrides): Promise<BigNumber>;

  balanceOf(
    account: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  balanceOfBatch(
    accounts: PromiseOrValue<string>[],
    ids: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  isApprovedForAll(
    account: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  mint(
    account: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  mintBatch(
    to: PromiseOrValue<string>,
    ids: PromiseOrValue<BigNumberish>[],
    amounts: PromiseOrValue<BigNumberish>[],
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  safeBatchTransferFrom(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    ids: PromiseOrValue<BigNumberish>[],
    amounts: PromiseOrValue<BigNumberish>[],
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  safeTransferFrom(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setApprovalForAll(
    operator: PromiseOrValue<string>,
    approved: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setURI(
    uri_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  uri(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    BOW(overrides?: CallOverrides): Promise<BigNumber>;

    BREAD(overrides?: CallOverrides): Promise<BigNumber>;

    CATTLE(overrides?: CallOverrides): Promise<BigNumber>;

    DATE(overrides?: CallOverrides): Promise<BigNumber>;

    EGG(overrides?: CallOverrides): Promise<BigNumber>;

    FLOUR(overrides?: CallOverrides): Promise<BigNumber>;

    GOLD(overrides?: CallOverrides): Promise<BigNumber>;

    GRAPE(overrides?: CallOverrides): Promise<BigNumber>;

    HEN(overrides?: CallOverrides): Promise<BigNumber>;

    IRON(overrides?: CallOverrides): Promise<BigNumber>;

    MEAT(overrides?: CallOverrides): Promise<BigNumber>;

    MILK(overrides?: CallOverrides): Promise<BigNumber>;

    PIG(overrides?: CallOverrides): Promise<BigNumber>;

    RICE(overrides?: CallOverrides): Promise<BigNumber>;

    SHEEP(overrides?: CallOverrides): Promise<BigNumber>;

    SHIELD(overrides?: CallOverrides): Promise<BigNumber>;

    SPEAR(overrides?: CallOverrides): Promise<BigNumber>;

    STONE(overrides?: CallOverrides): Promise<BigNumber>;

    SWORD(overrides?: CallOverrides): Promise<BigNumber>;

    WHEAT(overrides?: CallOverrides): Promise<BigNumber>;

    WOOD(overrides?: CallOverrides): Promise<BigNumber>;

    WOOL(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(
      account: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfBatch(
      accounts: PromiseOrValue<string>[],
      ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    isApprovedForAll(
      account: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    mint(
      account: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    mintBatch(
      to: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    safeBatchTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    safeTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setURI(
      uri_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    uri(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "ApprovalForAll(address,address,bool)"(
      account?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter;
    ApprovalForAll(
      account?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "TransferBatch(address,address,address,uint256[],uint256[])"(
      operator?: PromiseOrValue<string> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      ids?: null,
      values?: null
    ): TransferBatchEventFilter;
    TransferBatch(
      operator?: PromiseOrValue<string> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      ids?: null,
      values?: null
    ): TransferBatchEventFilter;

    "TransferSingle(address,address,address,uint256,uint256)"(
      operator?: PromiseOrValue<string> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      id?: null,
      value?: null
    ): TransferSingleEventFilter;
    TransferSingle(
      operator?: PromiseOrValue<string> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      id?: null,
      value?: null
    ): TransferSingleEventFilter;

    "URI(string,uint256)"(
      value?: null,
      id?: PromiseOrValue<BigNumberish> | null
    ): URIEventFilter;
    URI(value?: null, id?: PromiseOrValue<BigNumberish> | null): URIEventFilter;
  };

  estimateGas: {
    BOW(overrides?: CallOverrides): Promise<BigNumber>;

    BREAD(overrides?: CallOverrides): Promise<BigNumber>;

    CATTLE(overrides?: CallOverrides): Promise<BigNumber>;

    DATE(overrides?: CallOverrides): Promise<BigNumber>;

    EGG(overrides?: CallOverrides): Promise<BigNumber>;

    FLOUR(overrides?: CallOverrides): Promise<BigNumber>;

    GOLD(overrides?: CallOverrides): Promise<BigNumber>;

    GRAPE(overrides?: CallOverrides): Promise<BigNumber>;

    HEN(overrides?: CallOverrides): Promise<BigNumber>;

    IRON(overrides?: CallOverrides): Promise<BigNumber>;

    MEAT(overrides?: CallOverrides): Promise<BigNumber>;

    MILK(overrides?: CallOverrides): Promise<BigNumber>;

    PIG(overrides?: CallOverrides): Promise<BigNumber>;

    RICE(overrides?: CallOverrides): Promise<BigNumber>;

    SHEEP(overrides?: CallOverrides): Promise<BigNumber>;

    SHIELD(overrides?: CallOverrides): Promise<BigNumber>;

    SPEAR(overrides?: CallOverrides): Promise<BigNumber>;

    STONE(overrides?: CallOverrides): Promise<BigNumber>;

    SWORD(overrides?: CallOverrides): Promise<BigNumber>;

    WHEAT(overrides?: CallOverrides): Promise<BigNumber>;

    WOOD(overrides?: CallOverrides): Promise<BigNumber>;

    WOOL(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(
      account: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfBatch(
      accounts: PromiseOrValue<string>[],
      ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedForAll(
      account: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mint(
      account: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    mintBatch(
      to: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    safeBatchTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    safeTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setURI(
      uri_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    uri(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BOW(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    BREAD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CATTLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DATE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    EGG(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    FLOUR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    GOLD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    GRAPE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    HEN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    IRON(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MEAT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MILK(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PIG(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    RICE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SHEEP(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SHIELD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SPEAR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    STONE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SWORD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WHEAT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WOOD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WOOL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    balanceOf(
      account: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOfBatch(
      accounts: PromiseOrValue<string>[],
      ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isApprovedForAll(
      account: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mint(
      account: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    mintBatch(
      to: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    safeBatchTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      ids: PromiseOrValue<BigNumberish>[],
      amounts: PromiseOrValue<BigNumberish>[],
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    safeTransferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setURI(
      uri_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    uri(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
