/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Allocator,
  AllocatorInterface,
} from "../../../contracts/FOE.sol/Allocator";

const _abi = [
  {
    inputs: [],
    name: "getEraContractAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "dest",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdrawShare",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Allocator__factory {
  static readonly abi = _abi;
  static createInterface(): AllocatorInterface {
    return new utils.Interface(_abi) as AllocatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Allocator {
    return new Contract(address, _abi, signerOrProvider) as Allocator;
  }
}
