/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  BridgeERA,
  BridgeERAInterface,
} from "../../../../contracts/Bridge/Bridge.sol/BridgeERA";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ERA",
        name: "_ERA",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "destChain",
        type: "uint256",
      },
    ],
    name: "Locked",
    type: "event",
  },
  {
    inputs: [],
    name: "ERAContract",
    outputs: [
      {
        internalType: "contract ERA",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MINIMUM_THRESHOLD",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "destChain",
        type: "uint256",
      },
    ],
    name: "lock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052670de0b6b3a764000060005534801561001c57600080fd5b5060405161031038038061031083398101604081905261003b91610060565b600180546001600160a01b0319166001600160a01b039290921691909117905561008e565b600060208284031215610071578081fd5b81516001600160a01b0381168114610087578182fd5b9392505050565b6102738061009d6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80635297793b146100465780638b003ecf14610064578063cf27cfc414610079575b600080fd5b61004e61008e565b60405161005b91906101d3565b60405180910390f35b61006c61009d565b60405161005b9190610234565b61008c610087366004610178565b6100a3565b005b6001546001600160a01b031681565b60005481565b60005483116100cd5760405162461bcd60e51b81526004016100c4906101e7565b60405180910390fd5b600154604051632770a7eb60e21b81526001600160a01b0390911690639dc29fac906100ff90339087906004016101ba565b600060405180830381600087803b15801561011957600080fd5b505af115801561012d573d6000803e3d6000fd5b5050505080826001600160a01b03167f55016b6cc60c3d15b7b1ebd0ab766c07b3082c98a5b4d1d7ff012a97652a4b1d8560405161016b9190610234565b60405180910390a3505050565b60008060006060848603121561018c578283fd5b8335925060208401356001600160a01b03811681146101a9578283fd5b929592945050506040919091013590565b6001600160a01b03929092168252602082015260400190565b6001600160a01b0391909116815260200190565b6020808252602d908201527f416d6f756e74206d7573742062652067726561746572207468616e204d696e6960408201526c1b5d5b48151a1c995cda1bdb19609a1b606082015260800190565b9081526020019056fea2646970667358221220c3a198a62753d2861297a25b7058518312c0f91d4e7d1ceba2a0f40aabcf61d064736f6c63430008010033";

type BridgeERAConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BridgeERAConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BridgeERA__factory extends ContractFactory {
  constructor(...args: BridgeERAConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _ERA: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<BridgeERA> {
    return super.deploy(_ERA, overrides || {}) as Promise<BridgeERA>;
  }
  override getDeployTransaction(
    _ERA: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_ERA, overrides || {});
  }
  override attach(address: string): BridgeERA {
    return super.attach(address) as BridgeERA;
  }
  override connect(signer: Signer): BridgeERA__factory {
    return super.connect(signer) as BridgeERA__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BridgeERAInterface {
    return new utils.Interface(_abi) as BridgeERAInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BridgeERA {
    return new Contract(address, _abi, signerOrProvider) as BridgeERA;
  }
}
