/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as attachableNftSol from "./AttachableNFT.sol";
export type { attachableNftSol };
export type { HistopiaNFT } from "./HistopiaNFT";
export type { TypedNFT } from "./TypedNFT";
